<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Emby.Plugins.SegmentLoop</AssemblyName>
    <RootNamespace>Emby.Plugins.SegmentLoop</RootNamespace>
    <Version>1.1.23.0</Version>
    <EmbySystemPath Condition="'$(EmbySystemPath)' == ''">..\..\system</EmbySystemPath>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MediaBrowser.Common">
      <HintPath>$(EmbySystemPath)\MediaBrowser.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MediaBrowser.Controller">
      <HintPath>$(EmbySystemPath)\MediaBrowser.Controller.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MediaBrowser.Model">
      <HintPath>$(EmbySystemPath)\MediaBrowser.Model.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <EmbeddedResource Include="segmentloop.js" />
    <EmbeddedResource Include="config.html" />
    <EmbeddedResource Include="config.js" />
  </ItemGroup>
</Project>
